name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        python-version:
          - '3.8'
        arch:
          - 'x86_64'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies 
      run: |
        pip install --upgrade setuptools
        python -m pip install --upgrade pip
        sudo apt install build-essential python3-dev libsqlite3-dev openssl sqlite default-libmysqlclient-dev libmysqlclient-dev postgresql
        sudo apt-get install libmariadb-dev libmariadbclient-dev
        pip install .
        python setup.py install
        pip install pytest
        pip install .[async,google,amazon] \ --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-main/constraints-3.7.txt"   
        
    - name: test      
      run: |
       python -m pytest

