name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        python-version:
          - '3.8'
        arch:
          - 'x86_64'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies 
      run: |
        pip install --upgrade setuptools
        python -m pip install --upgrade pip
        sudo apt install build-essential python3-dev libsqlite3-dev openssl sqlite default-libmysqlclient-dev libmysqlclient-dev postgresql
        sudo apt-get install libmariadb-dev libmariadbclient-dev
        pip install .
        python setup.py install
        pip install pytest apache-airflow-breeze
        pip install .[async,google,amazon] \
        --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-main/constraints-3.7.txt" 
        pip install 'apache-airflow[postgres,google]==2.3.0' \
        --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.3.0/constraints-3.7.txt"
        pip3 install freezegun setproctitle kubernetes moto cachetools smbprotocol future boto3 celery lockfile pendulum werkzeug inflection httpx lazy_object_proxy tenacity croniter sqlalchemy_jsonfield psutil openapi_spec_validator jinja2 pygments cryptography colorlog flask cattrs dill tabulate flask_appbuilder flask_caching python-nvd3 markdown blinker marshmallow_oneofschema parameterized sentry-sdk pytest statsd psycopg2-binary requests-mock pandas elasticsearch paramiko 
        pip install oss2 google-api-core docker watchtower mypy-boto3-rds
        pip install cassandra-driver sqlparse pydruid hdfs
        pip install pandas google-api-python-client bson paramiko
        pip install asana cloudant databricks datadog elasticsearch
        pip install kylinpy pinotdb pyspark python-arango 
        pip install PyGithub httplib2 presto-python-client zenpy
        pip install vertica-python telegram tableauserverclient sshtunnel
        pip install snowflake slack-sdk pysftp sendgrid spython trino
        pip install yandexcloud cgroupspy bs4 grpcio redshift-connector 
        pip install jsonpath-ng pyexasol facebook-business qds_sdk simple-salesforce plyvel
        pip install pandas-gbq google-cloud-secret-manager google-cloud-redis devtools 
        pip install google-cloud-bigtable google-cloud-bigquery-datatransfer google-cloud-logging 
        pip install google-cloud-container looker-sdk google-cloud-language 
        pip install google-cloud-orchestration-airflow google-cloud-os-login 
        pip install google-cloud-workflows google-cloud-automl pypsrp
        pip install google-cloud-videointelligence google-cloud-datacatalog 
        pip install google-cloud-dataproc-metastore google-cloud-kms elasticsearch_dsl  
        pip install arango hmsclient azure-storage-blob sqlalchemy-databricks google-ads 
        pip install docker distributed google-cloud-dlp neo4j pymongo pywinrm
        pip install influxdb-client hvac azure-mgmt-datafactory azure-cosmos azure-storage-file 
        sudo apt install -y libkrb5-dev 
        pip install azureml-sdk kerberos gapic-google-cloud-spanner-v1 
        pip install cassandra-driver sqlalchemy-databricks azure-keyvault
        sudo apt install unixodbc-dev --yes && pip install pyodbc azure-mgmt-containerinstance azure-batch
        pip install mysqlclient azure-datalake-store pdpyras cx-Oracle opsgenie-sdk
        pip install proto-google-cloud-language-v1 google-cloud-pubsub google-cloud-speech redis arrow analytics papermill
    - name: test      
      run: |
       pytest

