name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        python-version:
          - '3.8'
        arch:
          - 'x86_64'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies 
      run: |
        pip install --upgrade setuptools
        python -m pip install --upgrade pip
        sudo apt-get install -y --no-install-recommends freetds-bin krb5-user ldap-utils libsasl2-2 libsasl2-modules libssl1.1 locales lsb-release sasl2-bin sqlite3 unixodbc
        python setup.py install
        pip install apache-airflow pytest 
        
    - name: test      
      run: |
        python -m pytest

  armv64_job:
    name: Build and Test for arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
           docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
             arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install git python3 python3-pip && apt-get install -y language-pack-en && export LC_CTYPE=en_US.UTF-8 && apt-get -y install locales && \
              pip3 install --upgrade setuptools && \
              python3 -m pip install -U pip && \
              pip3 install ez_setup && \
              pip3 install . && \
              python3 -m pip install pytest freezegun filelock celery kubernetes  boto3 moto apache-airflow-breeze apache-airflow-breeze parameterized sentry-sdk statsd distributed psycopg2-binary requests-mock oss2 google-api-core docker watchtower mypy-boto3-rds pandas google-api-python-client bson paramiko cassandra-driver sqlparse pydruid hdfs kylinpy pinotdb pyspark python-arango asana cloudant databricks datadog elasticsearch PyGithub httplib2 presto-python-client zenpy vertica-python telegram tableauserverclient sshtunnel snowflake slack-sdk pysftp sendgrid spython trino yandexcloud cgroupspy bs4 Flask-MySQLdb grpcio redshift-connector jsonpath-ng pyexasol facebook-business qds_sdk simple-salesforce plyvel && \
              pytest && \
              deactivate'
